### ISSUE TITLE
The timer select not working

### ISSUE THREAD

**Issue by rusnnee** [nicolasdhnr/Koalingo#43]
The timer selection in host/lobby is not working any more

**Comment by iib0011** [comment]
Hi. Can you document the project? I want to setup locally and contribute

**Comment by nicolasdhnr** [comment]
Hi @iib0011 Thanks for your interest! We're getting it all written up right now and we'll be able to get back to you later this week :) thank you so much for wanting to contribute, would be happy to email you about it (my email is in the README)

**Comment by iib0011** [comment]
Here is my email: ibracool99@gmail.com. Just create issues and  I will try to work on them.

**Comment by iib0011** [comment]
Also don't forget to add topics to the repo to get more visibility
